import { useEffect, useState } from 'react'
import { authFetch } from '../lib/auth'

/* Content & SEO — admin view of the blog pipeline.
   Data comes from /api/content, which serves backend/content_status.json.
   That file is regenerated by the SEO AUTOMATION project
   (scripts/build_content_status.py); this screen is read-only on purpose —
   nothing here publishes, because every change goes through a reviewed PR. */

interface PostImage { file: string; role: string; alt: string; type?: string }

interface Post {
  slug: string
  title: string
  url: string
  state: 'published' | 'draft'
  publish_date?: string
  word_count?: number
  primary_keyword?: string
  meta_title?: string
  meta_title_len?: number
  meta_description_len?: number
  sources?: number
  internal_links?: number
  images?: PostImage[]
  research?: string[]
  checks_passed?: number
  checks_open?: number
  open_items?: string[]
}

interface QueueItem {
  n: string; topic: string; intent: string; audience: string
  why: string; risk: string; state: 'written' | 'planned'
}

interface Tripwire { id: string; fact: string; breaks: string }
interface GeoEntry { date: string; body: string }

interface ContentData {
  available: boolean
  reason?: string
  generated?: string
  reviewer?: string
  summary?: Record<string, number>
  posts: Post[]
  queue: QueueItem[]
  tripwires: Tripwire[]
  geo_citations: GeoEntry[]
  notes?: string[]
}

type Tab = 'posts' | 'queue' | 'health'

export default function ContentPage() {
  const [data, setData] = useState<ContentData | null>(null)
  const [err, setErr] = useState('')
  const [tab, setTab] = useState<Tab>('posts')
  const [open, setOpen] = useState<string | null>(null)

  useEffect(() => {
    authFetch('/api/content')
      .then((r) => {
        if (r.status === 403) throw new Error('Admins only.')
        if (!r.ok) throw new Error(`Could not load (${r.status})`)
        return r.json()
      })
      .then(setData)
      .catch((e) => setErr(e.message || 'Could not load content status'))
  }, [])

  if (err) return <main className="settings-page"><p className="idle-hint">{err}</p></main>
  if (!data) return <main className="settings-page"><p className="idle-hint">Loading…</p></main>

  if (!data.available) {
    return (
      <main className="settings-page">
        <section className="setting-block">
          <h3>Nothing to show yet</h3>
          <p className="idle-hint" style={{ textAlign: 'left' }}>
            {data.reason || 'The content pipeline has not published a status file yet.'}
          </p>
          <p className="idle-hint" style={{ textAlign: 'left' }}>
            Generate it with <code>python3 scripts/build_content_status.py</code> in the
            SEO AUTOMATION project, then commit <code>backend/content_status.json</code>.
          </p>
        </section>
      </main>
    )
  }

  const s = data.summary || {}
  const cards: [string, number, string][] = [
    ['Published', s.published ?? 0, 'live on the site'],
    ['Drafts', s.drafts ?? 0, 'written, not shipped'],
    ['Queued', s.queued ?? 0, 'on the calendar'],
    ['Open items', s.open_items ?? 0, 'unfinished checks'],
  ]

  return (
    <main className="settings-page">
      <div className="cost-cards">
        {cards.map(([label, value, hint]) => (
          <div className="cost-card" key={label}>
            <small>{label}</small>
            <b>{value}</b>
            <span>{hint}</span>
          </div>
        ))}
      </div>

      <div className="content-tabs">
        {([['posts', 'Posts'], ['queue', 'Calendar'], ['health', 'Health']] as [Tab, string][])
          .map(([k, label]) => (
            <button
              key={k}
              className={`content-tab${tab === k ? ' is-on' : ''}`}
              aria-pressed={tab === k}
              onClick={() => {
                setTab(k)
                setOpen(null)
                window.scrollTo({ top: 0 })
              }}
            >
              {label}
            </button>
          ))}
      </div>

      {tab === 'posts' && (
        <section className="setting-block">
          <h3>Posts</h3>
          {data.posts.length === 0 && (
            <p className="idle-hint" style={{ textAlign: 'left' }}>No posts yet.</p>
          )}
          {data.posts.map((p) => {
            const isOpen = open === p.slug
            return (
              <div className="content-row" key={p.slug}>
                <button className="content-head" onClick={() => setOpen(isOpen ? null : p.slug)}>
                  <span className={`pill pill-${p.state}`}>
                    {p.state === 'published' ? 'Live' : 'Draft'}
                  </span>
                  <span className="content-title">{p.title}</span>
                  <span className="content-chev">{isOpen ? '−' : '+'}</span>
                </button>

                {isOpen && (
                  <div className="content-detail">
                    <dl className="content-facts">
                      <div><dt>URL</dt><dd>
                        <a href={p.url} target="_blank" rel="noreferrer">{p.url}</a>
                      </dd></div>
                      <div><dt>Primary keyword</dt><dd>{p.primary_keyword || '—'}</dd></div>
                      <div><dt>Words</dt><dd>{p.word_count ?? '—'}</dd></div>
                      <div><dt>Sourced claims</dt><dd>{p.sources ?? 0}</dd></div>
                      <div><dt>Internal links</dt><dd>{p.internal_links ?? 0}</dd></div>
                      <div><dt>Meta title</dt><dd>
                        {p.meta_title_len ?? 0}/60
                        {(p.meta_title_len ?? 0) > 60 && <b className="bad"> too long</b>}
                      </dd></div>
                      <div><dt>Meta description</dt><dd>
                        {p.meta_description_len ?? 0}/150–160
                        {((p.meta_description_len ?? 0) < 150 || (p.meta_description_len ?? 0) > 160)
                          && <b className="bad"> out of range</b>}
                      </dd></div>
                      <div><dt>QA checks</dt><dd>
                        {p.checks_passed ?? 0} passed
                        {(p.checks_open ?? 0) > 0 && ` · ${p.checks_open} open`}
                      </dd></div>
                    </dl>

                    {!!p.open_items?.length && (
                      <>
                        <h4 className="content-h4">Still open</h4>
                        <ul className="content-list">
                          {p.open_items.map((t, i) => <li key={i}>{t}</li>)}
                        </ul>
                      </>
                    )}

                    {!!p.images?.length && (
                      <>
                        <h4 className="content-h4">Images</h4>
                        <div className="content-imgs">
                          {p.images.map((im) => (
                            <figure className="content-img" key={im.file}>
                              <img src={`/img/blog/${im.file}`} alt={im.alt} loading="lazy" />
                              <figcaption>{im.role}{im.type ? ` · ${im.type}` : ''}</figcaption>
                            </figure>
                          ))}
                        </div>
                      </>
                    )}

                    {!!p.research?.length && (
                      <>
                        <h4 className="content-h4">Research on file</h4>
                        <ul className="content-list">
                          {p.research.map((r) => <li key={r}><code>{r}</code></li>)}
                        </ul>
                      </>
                    )}
                  </div>
                )}
              </div>
            )
          })}
        </section>
      )}

      {tab === 'queue' && (
        <section className="setting-block">
          <h3>Content calendar</h3>
          <p className="idle-hint" style={{ textAlign: 'left' }}>
            Priorities are reasoned from search results, not measured volume — no keyword
            tool is connected.
          </p>
          {data.queue.map((q) => (
            <div className="queue-row" key={q.n + q.topic}>
              <span className={`pill pill-${q.state === 'written' ? 'published' : 'planned'}`}>
                {q.state === 'written' ? 'Written' : `#${q.n}`}
              </span>
              <div className="queue-body">
                <b>{q.topic}</b>
                <span>{q.intent} · {q.audience}</span>
                <span className="queue-why">{q.why}</span>
              </div>
            </div>
          ))}
        </section>
      )}

      {tab === 'health' && (
        <>
          <section className="setting-block">
            <h3>Freshness tripwires</h3>
            <p className="idle-hint" style={{ textAlign: 'left' }}>
              Facts that would make a published post wrong if they changed. Checked monthly.
            </p>
            {data.tripwires.map((t) => (
              <div className="trip-row" key={t.id}>
                <code>{t.id}</code>
                <b>{t.fact}</b>
                <span>{t.breaks}</span>
              </div>
            ))}
          </section>

          <section className="setting-block">
            <h3>AI citation checks</h3>
            {data.geo_citations.length === 0 ? (
              <p className="idle-hint" style={{ textAlign: 'left' }}>
                No baseline recorded yet. There is no ChatGPT / Gemini / Perplexity connector,
                so these have to be run by hand — the six questions are in the runbook.
              </p>
            ) : (
              data.geo_citations.map((g) => (
                <div className="trip-row" key={g.date}>
                  <b>{g.date}</b>
                  <span style={{ whiteSpace: 'pre-wrap' }}>{g.body}</span>
                </div>
              ))
            )}
          </section>

          {!!data.notes?.length && (
            <section className="setting-block">
              <h3>Known limits</h3>
              <ul className="content-list">
                {data.notes.map((n, i) => <li key={i}>{n}</li>)}
              </ul>
            </section>
          )}
        </>
      )}

      <p className="idle-hint" style={{ marginTop: 18 }}>
        Generated {data.generated || '—'}
        {data.reviewer && ` · reviewer: ${data.reviewer}`}
        <br />Read-only. Posts ship through a reviewed pull request.
      </p>
    </main>
  )
}
